### ISSUE TITLE
sphere_shade and water issues

### ISSUE THREAD

**Issue by Euconnus** [tylermorganwall/rayshader#17] opened 2018-10-05 15:20 UTC
Hello guys,

First of all big, BIG thanks for this beautiful package ! Awesome work.

Almost everything works perfect in my tests, except for two functions that always throw error messages. As they are useful and major functions, this is quite annoying :

- **sphere_shade** (although every other shading function works fine : ray_shade, lamb_shade, ambient_shade, so I guess my data/params are OK) which throws :

> Error in temp[2:(nrow(temp) - 1), 2:(ncol(temp) - 1)] <- heightmap : 
>   number of items to replace is not a multiple of replacement length 

- **water=TRUE** in **plot_3d(...)** which always results in :

> Error in if (heightmap2[i] < waterheight) { : 
> missing value where TRUE/FALSE needed

Do you have any idea how to avoid these "crashes" ?

**Comment by tylermorganwall** [comment] 2018-10-08 17:19
Hi,
It looks like there is an issue with your dataset. Does the code work on the `montereybay` dataset included with rayshader?

**Comment by Euconnus** [comment] 2018-10-10 09:04
Hi,
Yes it works fine with montereybay. I think the first issue was I was using sphere_shade as the other shading functions though the return value isn't the same. Now I can get the function working but the result is quite surprising. I already have a texture for the elevation map, and I guess you can't keep it unmodified once sphere_shade is called, while the other shading procedures allow to keep the texture unmodified and add the shading.
I still can't understand the second issue with water though...  The water still appears despite the error message, but just the surface, not water line and no filling.

**Comment by gustavo-etal** [comment] 2018-11-04 18:43
I am trying it out but I am not sure why this background is here and why the zoom is not working 
![image](https://user-images.githubusercontent.com/42280272/47968412-93112e80-e037-11e8-9484-3e2acef449d1.png)

**Comment by tylermorganwall** [comment] 2018-11-06 15:31
> Hi,
> Yes it works fine with montereybay. I think the first issue was I was using sphere_shade as the other shading functions though the return value isn't the same, and I'm not quite sure what "a square matrix indicating the spherical texture mapping" exactly is. Now I can get the function working but the result is quite surprising. I already have a texture for the elevation map, and I can't keep it unmodified once sphere_shade is called, while the other shading procedures allow to keep the texture unmodified and add the shading.
> I still can't understand the second issue with water though... The water still appears despite the error message, but just the surface, no water line and no filling.

I really need a reproducible example to hunt down any bugs--I'm not exactly sure what's causing your problem, but it would be easier to diagnose if you can provide the dataset and the exact code used to produce the error.

**Comment by tylermorganwall** [comment] 2018-11-09 16:05
I'm going to close this--if you are still having an issue and can post a reproducible example, feel free to re-open.

**Closed by tylermorganwall** 2018-11-09 16:05 UTC
