### ISSUE TITLE
Error: Singular matrix in MatrixInvert

### ISSUE THREAD

**Issue by wiesehahn** [tylermorganwall/rayshader#315] opened 2024-07-24 21:00 UTC
**Describe the bug**
When trying to render a scene I come across "Error: Singular matrix in MatrixInvert"

**Session Info**

```r
> sessionInfo()
R version 4.4.0 Patched (2024-05-20 r86569 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 17763)

Matrix products: default


locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lasR_0.9.1     lidR_4.1.2     devtools_2.4.5 usethis_2.2.3 

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.1       viridisLite_0.4.2      dplyr_1.1.4           
 [4] viridis_0.6.5          lazyeval_0.2.2         fastmap_1.2.0         
 [7] promises_1.3.0         reprex_2.1.0           digest_0.6.35         
[10] mime_0.12              lifecycle_1.0.4        sf_1.0-16             
[13] rlas_1.7.0             ellipsis_0.3.2         processx_3.8.4        
[16] terra_1.7-78           magrittr_2.0.3         compiler_4.4.0        
[19] rlang_1.1.3            progress_1.2.3         tools_4.4.0           
[22] utf8_1.2.4             yaml_2.3.9             data.table_1.15.4     
[25] knitr_1.48             prettyunits_1.2.0      htmlwidgets_1.6.4     
[28] pkgbuild_1.4.4         classInt_0.4-10        curl_5.2.1            
[31] here_1.0.1             pkgload_1.3.4          KernSmooth_2.23-24    
[34] miniUI_0.1.1.1         withr_3.0.0            purrr_1.0.2           
[37] desc_1.4.3             grid_4.4.0             rgl_1.3.1             
[40] fansi_1.0.6            urlchecker_1.0.1       profvis_0.3.8         
[43] colorspace_2.1-0       xtable_1.8-4           e1071_1.7-14          
[46] ggplot2_3.5.1          scales_1.3.0           iterators_1.0.14      
[49] cli_3.6.2              rmarkdown_2.27         rayshader_0.37.3      
[52] crayon_1.5.2           generics_0.1.3         remotes_2.5.0         
[55] rstudioapi_0.16.0      sessioninfo_1.2.2      DBI_1.2.3             
[58] cachem_1.1.0           proxy_0.4-27           managelidar_0.0.0.9000
[61] stringr_1.5.1          parallel_4.4.0         base64enc_0.1-3       
[64] vctrs_0.6.5            jsonlite_1.8.8         callr_3.7.6           
[67] hms_1.1.3              foreach_1.5.2          clipr_0.8.0           
[70] units_0.8-5            glue_1.7.0             rayrender_0.32.2      
[73] codetools_0.2-20       ps_1.7.6               stringi_1.8.4         
[76] gtable_0.3.5           later_1.3.2            rayvertex_0.11.4      
[79] munsell_0.5.1          tibble_3.2.1           pillar_1.9.0          
[82] htmltools_0.5.8.1      R6_2.5.1               rprojroot_2.0.4       
[85] doParallel_1.0.17      rayimage_0.11.0        evaluate_0.24.0       
[88] shiny_1.8.1.1          png_0.1-8              memoise_2.0.1         
[91] httpuv_1.6.15          class_7.3-22           Rcpp_1.0.12           
[94] gridExtra_2.3          xfun_0.45              fs_1.6.4              
[97] pkgconfig_2.0.3  
```
**Reproducible Example**

```r


library(lasR)
f <- system.file("extdata", "Megaplot.las", package = "lasR")
pipeline <-
  dtm(ofile = paste0(tempdir(), "*dtm.tif")) +
  normalize(extrabytes = TRUE) +
  write_las(filter = "-drop_z_below 0.1 -drop_ground", ofile = paste0(tempdir(), "*nlas.las"))
ans <- exec(pipeline, on = f)


# init 3D plot with DTM
elmat <- rayshader::raster_to_matrix(ans$rasterize)
elmat |> 
  rayshader::sphere_shade(zscale = 0.25, 
               texture= rayshader::create_texture("white","brown","white","white","white")
  ) |> 
  rayshader::add_shadow(rayshader::ray_shade(elmat), 0.6)  |> 
  rayshader::plot_3d(elmat, zscale = 1, fov = 45, theta = 1, zoom = 0.6, phi = 89, windowsize = c(500, 500), solid=FALSE) 

# add vegetation points
points <- lidR::readLAS(ans$write_las)
rayshader::render_points(extent = lidR::ext(points),
              lat = points@data$Y,
              long = points@data$X,
              altitude = points@data$Z,
              zscale=1,
              offset = 0,
              color=viridis::plasma(length(points@data$Z))[rank(points@data$Z)],
              size = 3)


# get environment light scene
hdr <- tempfile(fileext = ".hdr")
download.file("https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/2k/kiara_1_dawn_2k.hdr", hdr)


# render scene
rayshader::render_highquality(point_radius = 3,
                   parallel = TRUE,
                   light = FALSE,
                   environment_light = hdr,
                   clear = TRUE,
                   width = 1000,
                   height = 1000,
                   filename = here::here("figures", "raytraced_pointcloud.png")
)
```

**Comment by JJFoest** [comment] 2024-10-16 13:49
Perhaps, the issue is in the render_points? I run into the very same error, and it disappeared when I removed render_points()

**Comment by polc1410** [comment] 2024-12-11 01:57
I'm hitting this bug.

I am using render_points.  When I reproduce from [this page](https://github.com/milos-agathon/3d-light-bubble-map&v=nlSu5-Ueuqo) - all is good.  But when I change the data for my own plot I'm getting the error.

I can't see what I can be doing wrong that causes it.  If anyone found a solution I'm keen to hear about it?

Do we know if this is version specific?

**Comment by wiesehahn** [comment] 2024-12-17 12:20
I am still struggling with this problem, but I am getting a little closer to find the cause.

- It has to do with the rendered points
- It has to do with certain points 
- when I convert point coordinates to integer or round to 0 decimals it works

**Comment by tylermorganwall** [comment] 2024-12-24 04:50
Thank you for the bug report: this was due to that particular DEM having NA edge points, which resulted in NA values when points tried to interpolate the nearest edge point and then issues when constructing the scene. This should be fixed in the latest version of rayshader, which removes these points that can't be interpolated.

**Closed by tylermorganwall** 2024-12-24 04:50 UTC
Labels: bug
